version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ozon_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    command: ["./main"]
    ports:
        - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: ozon_db
      STORAGE_TYPE: ${STORAGE_TYPE:-postgres}
